name: Arduino Library Deploy
description: A Docker-based GitHub Action to validate, merge PRs, and create releases.
branding:
  icon: "archive"
  color: "green"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token for API requests."
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.GITHUB_TOKEN }}
